DROP TABLE IF EXISTS transactions CASCADE;

DROP TABLE IF EXISTS deposits CASCADE;

DROP TABLE IF EXISTS credits CASCADE;

DROP TABLE IF EXISTS user_accounts CASCADE;

DROP TABLE IF EXISTS cards CASCADE;

DROP TABLE IF EXISTS accounts CASCADE;

DROP TABLE IF EXISTS account_types CASCADE;

DROP TABLE IF EXISTS card_types CASCADE;

DROP TABLE IF EXISTS user_data CASCADE;

DROP TABLE IF EXISTS users CASCADE;






